provider "fastly" {
  # Reads from FASTLY_API_KEY environment variable
}

resource "fastly_service_vcl" "gnome_domains" {
  name = var.service_name

  # ── Domains ──
  # All proxy and redirect domains, populated by generate-tfvars.py
  dynamic "domain" {
    for_each = toset(var.all_domains)
    content {
      name = domain.value
    }
  }

  # ── Backends ──

  dynamic "backend" {
    for_each = var.backends
    content {
      name                  = backend.key
      address               = backend.value.address
      port                  = 443
      use_ssl               = true
      ssl_cert_hostname     = backend.value.address
      ssl_sni_hostname      = backend.value.address
      ssl_check_cert        = true
      auto_loadbalance      = false
      max_conn              = lookup(backend.value, "max_conn", 200)
      connect_timeout       = 5000
      first_byte_timeout    = 15000
      between_bytes_timeout = 10000
      shield                = "iad-va-us"
    }
  }

  # ── Edge Dictionaries ──

  dictionary {
    name = "domain_to_path"
  }

  dictionary {
    name = "domain_to_origin_host"
  }

  dictionary {
    name = "simple_redirects"
  }

  dictionary {
    name = "redirect_preserve_path"
  }

  # ── Force TLS ──
  request_setting {
    name      = "force-tls"
    force_ssl = true
  }

  # ── HSTS ──
  header {
    name        = "HSTS"
    action      = "set"
    type        = "response"
    destination = "http.Strict-Transport-Security"
    source      = "\"max-age=31536000; includeSubDomains; preload\""
  }

  # ── Custom VCL ──
  # main.vcl is the entry point; generated VCL files are included
  # dynamically based on which TOML configs have vcl_snippet set.

  vcl {
    name    = "main"
    content = file("${path.module}/vcl/main.vcl")
    main    = true
  }

  dynamic "vcl" {
    for_each = toset(var.vcl_snippets)
    content {
      name    = vcl.value
      content = file("${path.module}/vcl/${vcl.value}.vcl")
      main    = false
    }
  }

  force_destroy = false
}

# ── TLS ──
# Fastly-managed Let's Encrypt certificates, grouped by domain family.
# Groups are generated by generate-tfvars.py using wildcards where beneficial.

resource "fastly_tls_subscription" "domain_certs" {
  for_each = var.tls_groups

  domains               = each.value
  certificate_authority = "lets-encrypt"
}

# ── Dictionary Items ──
# Populated from the TOML files via generate-tfvars.py

locals {
  dict_ids = {
    for d in fastly_service_vcl.gnome_domains.dictionary :
    d.name => d.dictionary_id
  }
}

resource "fastly_service_dictionary_items" "domain_to_path" {
  count = length(var.domain_to_path) > 0 ? 1 : 0

  service_id    = fastly_service_vcl.gnome_domains.id
  dictionary_id = local.dict_ids["domain_to_path"]

  items = var.domain_to_path

  manage_items = true
}

resource "fastly_service_dictionary_items" "domain_to_origin_host" {
  count = length(var.domain_to_origin_host) > 0 ? 1 : 0

  service_id    = fastly_service_vcl.gnome_domains.id
  dictionary_id = local.dict_ids["domain_to_origin_host"]

  items = var.domain_to_origin_host

  manage_items = true
}

resource "fastly_service_dictionary_items" "simple_redirects" {
  count = length(var.simple_redirects) > 0 ? 1 : 0

  service_id    = fastly_service_vcl.gnome_domains.id
  dictionary_id = local.dict_ids["simple_redirects"]

  items = var.simple_redirects

  manage_items = true
}

resource "fastly_service_dictionary_items" "redirect_preserve_path" {
  count = length(var.redirect_preserve_path) > 0 ? 1 : 0

  service_id    = fastly_service_vcl.gnome_domains.id
  dictionary_id = local.dict_ids["redirect_preserve_path"]

  items = var.redirect_preserve_path

  manage_items = true
}
