[[redirects]]
domain = "projects.gnome.org"
vcl_snippet = "projects"
default_redirect = "https://wiki.gnome.org/Apps"

[redirects.path_redirects]
"/" = "https://wiki.gnome.org/Apps"
"/accessibility" = "https://wiki.gnome.org/Accessibility"
"/outreach/a11y" = "https://wiki.gnome.org/Outreach/Accessibility/"
"/outreach" = "https://wiki.gnome.org/Outreach"
"/gnome-db" = "http://www.gnome-db.org/"
"/sabayon" = "https://wiki.gnome.org/Sabayon"
"/NetworkManager" = "https://wiki.gnome.org/Projects/NetworkManager"
"/libchamplain" = "https://wiki.gnome.org/Projects/libchamplain"
"/nanny" = "https://wiki.gnome.org/Projects/Nanny"
"/tracker" = "https://wiki.gnome.org/Projects/Tracker"
"/nautilus-python" = "https://wiki.gnome.org/Projects/NautilusPython"
"/nautilus-sound-converter" = "https://wiki.gnome.org/Projects/NautilusSoundConverter"
"/orca" = "https://wiki.gnome.org/Projects/Orca"
"/gdm" = "https://wiki.gnome.org/Projects/GDM"
"/gtksourceview" = "https://wiki.gnome.org/Projects/GtkSourceView"
"/gtksourceviewmm" = "https://developer.gnome.org/gtksourceviewmm/"
"/libgsf" = "https://developer.gnome.org/gsf/"
"/diagnome" = "https://wiki.gnome.org/Events/DiaGNOME"
"/anjuta" = "https://wiki.gnome.org/Apps/Anjuta"
"/brasero" = "https://wiki.gnome.org/Apps/Brasero"
"/cheese" = "https://wiki.gnome.org/Apps/Cheese"
"/dia" = "https://wiki.gnome.org/Apps/Dia"
"/easytag" = "https://wiki.gnome.org/Apps/EasyTAG"
"/eog" = "https://wiki.gnome.org/Apps/EyeOfGnome"
"/epiphany" = "https://wiki.gnome.org/Apps/Web"
"/evince" = "https://wiki.gnome.org/Apps/Evince"
"/gedit" = "https://wiki.gnome.org/Apps/Gedit"
"/gyrus" = "https://wiki.gnome.org/Apps/Gyrus"
"/hipo" = "https://wiki.gnome.org/Apps/Hipo"
"/hotssh" = "https://wiki.gnome.org/Apps/HotSSH"
"/latexila" = "https://wiki.gnome.org/Apps/LaTeXila"
"/nemiver" = "https://wiki.gnome.org/Apps/Nemiver"
"/postr" = "https://wiki.gnome.org/Apps/Postr"
"/rhythmbox" = "https://wiki.gnome.org/Apps/Rhythmbox"
"/seahorse" = "https://wiki.gnome.org/Apps/Seahorse"
"/snappy" = "https://wiki.gnome.org/Apps/Snappy"
"/tomboy" = "https://wiki.gnome.org/Apps/Tomboy"
"/totem" = "https://wiki.gnome.org/Apps/Videos"
"/vinagre" = "https://wiki.gnome.org/Apps/Vinagre"
"/yelp" = "https://wiki.gnome.org/Apps/Yelp"
"/memprof" = "https://wiki.gnome.org/Apps/MemProf"
"/gtranslator" = "https://wiki.gnome.org/Apps/Gtranslator"
"/emerillon" = "https://wiki.gnome.org/Apps/Emerillon"
"/evolution" = "https://wiki.gnome.org/Apps/Evolution"
"/straw" = "https://wiki.gnome.org/Apps/Attic/Straw"
"/gnumeric" = "http://www.gnumeric.org"

[[redirects]]
domain = "projects-old.gnome.org"
target = "https://projects.gnome.org"
type = "permanent"
preserve_path = true
