[[pages]]
domain = "tools.design.gnome.org"
origin = "https://world.pages.gitlab.gnome.org/design/tools/"

[[pages]]
domain = "icons.design.gnome.org"
origin = "https://teams.pages.gitlab.gnome.org/Design/icon-development-kit/"
