[[pages]]
domain = "developer.gnome.org"
origin = "https://teams.pages.gitlab.gnome.org/Websites/developer.gnome.org/"
vcl_snippet = "developer"

[pages.subpath_proxies]
"/hig/" = "/Websites/developer.gnome.org-hig/"
"/components/" = "/Websites/developer.gnome.org-components/"

[pages.path_redirects]
"/Jhbuild" = "https://wiki.gnome.org/Projects/Jhbuild/Introduction"
"/glib" = "https://docs.gtk.org/glib/"
"/gobject" = "https://docs.gtk.org/gobject/"
"/gio" = "https://docs.gtk.org/gio/"
"/gtk3" = "https://docs.gtk.org/gtk3/"
"/gdk3" = "https://docs.gtk.org/gdk3/"
"/atk" = "https://gnome.pages.gitlab.gnome.org/atk/"
"/libsigc++" = "https://libsigcplusplus.github.io/libsigcplusplus/reference/html/"
"/glibmm" = "https://gnome.pages.gitlab.gnome.org/glibmm/"
"/gtkmm" = "https://gnome.pages.gitlab.gnome.org/gtkmm/"
"/gtkmm-tutorial" = "https://gnome.pages.gitlab.gnome.org/gtkmm-documentation/"
"/NetworkManager" = "https://networkmanager.dev/docs/api/latest/"
"/libnm" = "https://networkmanager.dev/docs/libnm/latest/"
"/pango" = "https://docs.gtk.org/Pango/"
"/libsoup/" = "https://libsoup.gnome.org/"
"/platform-overview/unstable" = "https://developer.gnome.org/"
"/guides" = "https://developer.gnome.org/"
"/AlternateMenubarLayout" = "https://developer.gnome.org/"
"/AppFolders" = "https://developer.gnome.org/"
"/ChooseApplicationID" = "https://developer.gnome.org/"
"/Buttons" = "https://developer.gnome.org/"
"/CustomStyle" = "https://developer.gnome.org/"
"/Deprecations" = "https://developer.gnome.org/"
"/DragAndDrop" = "https://developer.gnome.org/"
"/Dialogs" = "https://developer.gnome.org/"
"/ExtractShell" = "https://developer.gnome.org/"
"/GAction" = "https://developer.gnome.org/"
"/GNotification" = "https://developer.gnome.org/"
"/Gestures" = "https://developer.gnome.org/"
"/CommandLine" = "https://developer.gnome.org/"
"/ClutterGstGirPython" = "https://developer.gnome.org/"
"/Labels" = "https://developer.gnome.org/"
"/ApplicationMenu" = "https://developer.gnome.org/"
"/SaveWindowState" = "https://developer.gnome.org/"
"/SearchProvider" = "https://developer.gnome.org/"
"/DBusApplicationLaunching" = "https://developer.gnome.org/"
"/SubclassGObject" = "https://developer.gnome.org/"
"/ThemedIcons" = "https://developer.gnome.org/"
"/GMenu" = "https://developer.gnome.org/"
"/GSettings" = "https://developer.gnome.org/"
"/GtkApplication" = "https://developer.gnome.org/"
