[[pages]]
domain = "2003.guadec.org"
origin = "https://infrastructure.pages.gitlab.gnome.org/guadec-archive/2003/"

[[pages]]
domain = "2004.guadec.org"
origin = "https://infrastructure.pages.gitlab.gnome.org/guadec-archive/2004/"

[[pages]]
domain = "2005.guadec.org"
origin = "https://infrastructure.pages.gitlab.gnome.org/guadec-archive/2005/"

[[pages]]
domain = "2013.guadec.org"
origin = "https://infrastructure.pages.gitlab.gnome.org/guadec-archive/2013/"

[[pages]]
domain = "2014.guadec.org"
origin = "https://infrastructure.pages.gitlab.gnome.org/guadec-archive/2014/"

[[pages]]
domain = "2015.guadec.org"
origin = "https://infrastructure.pages.gitlab.gnome.org/guadec-archive/2015/"

[[pages]]
domain = "2016.guadec.org"
origin = "https://infrastructure.pages.gitlab.gnome.org/guadec-archive/2016/"

[[pages]]
domain = "2017.guadec.org"
origin = "https://infrastructure.pages.gitlab.gnome.org/guadec-archive/2017/"

[[pages]]
domain = "2018.guadec.org"
origin = "https://infrastructure.pages.gitlab.gnome.org/guadec-archive/2018/"
