[[pages]]
domain = "os.gnome.org"
origin = "https://teams.pages.gitlab.gnome.org/Releng/gnome-os-site/"
vcl_snippet = "os"
custom_vcl = """
  if (req.url ~ "^/download(/|$)") {
    set req.backend = F_gnome_os_download;
    set req.http.Host = "gnome-os-download.apps.openshift.gnome.org";
    set req.url = regsub(req.url, "^/download", "");
    return(lookup);
  }
"""
