[[pages]]
domain = "teams.gnome.org"
vcl_snippet = "teams"
custom_vcl = """
  if (req.url == "/platform") {
    error 751 "https://teams.gnome.org/platform/";
  }
  if (req.url ~ "^/platform/") {
    set req.backend = F_gitlab_pages;
    set req.http.X-Orig-Host = req.http.Host;
    set req.http.Host = "teams.pages.gitlab.gnome.org";
    set req.url = "/Platform/General/" regsub(req.url, "^/platform/", "");
    unset req.http.X-Forwarded-Host;
    return(lookup);
  }
"""
